version: "3"

env:
  VELERO_PLUGIN_VERSION: v1.7.1
  PLATFORM: sulfoxide
  SERVICE: fluorine
  MODULE: store
  VELERO_REGION: APAC

includes:
  setup: tasks/Taskfile.setup.yaml
  velero:suicune:
    taskfile: tasks/Taskfile.velero.yaml
    vars:
      LANDSCAPE: suicune
      VELERO_S3_URL: https://177aa484a66427793543c5e958f8d020.r2.cloudflarestorage.com

tasks:
  # Utility
  start:cluster:
    desc: Starts the playground cluster to test helm charts
    cmds:
      - ./scripts/local/create-k3d-cluster.sh

  stop:cluster:
    desc: Destroys the playground cluster to test helm charts
    cmds:
      - ./scripts/local/delete-k3d-cluster.sh

  migrate:
    desc: Migrate cluster
    cmds:
      - ./scripts/migrate.sh {{.CLI_ARGS}}
