version: "3"

tasks:
  default:
    desc: Setup the repository by syncing secrets
    cmds:
      - ./scripts/local/secrets.sh
      - task: suicune:secret
  secret:
    desc: Download secrets
    internal: true
    cmds:
      - infisical run --env={{.LANDSCAPE}} -- gomplate -f ./secret.tpl > "{{.LANDSCAPE}}.secret"

  suicune:secret:
    desc: Download secrets for suicune
    cmds:
      - task: secret
        vars:
          LANDSCAPE: suicune
